#!/bin/bash
# Script para activar el orquestador manualmente

echo "🎭 Activando Dream Team Orchestrator..."
echo ""
echo "Modos de uso:"
echo ""
echo "1. MODO AUTOMÁTICO (Recomendado):"
echo "   El orquestador detectará automáticamente tareas complejas"
echo "   y coordinará los agentes necesarios."
echo ""
echo "2. MODO MANUAL:"
echo "   Menciona explícitamente en tu prompt:"
echo "   > 'Usando el orquestador, crea una app full-stack'"
echo ""
echo "3. ACTIVAR PARA TODA LA SESIÓN:"
echo "   > opencode --agent orchestrator"
echo ""
echo "El orquestador analizará tu tarea y:"
echo "  ✓ Determinará la complejidad"
echo "  ✓ Seleccionará los agentes apropiados"
echo "  ✓ Planificará el flujo de trabajo"
echo "  ✓ Coordinará la ejecución"
echo ""
